const ToastConstants = Object.freeze({
    TOAST_EXIT_APP: 'Tap back button again to exit',
    TOAST_NO_VOC: 'You have no vocabulary',
    TOAST_ADD_WORDS_TO_VOC: 'Please add some words/expressions to your vocabulary',
    TOAST_UNEXPECTED_LEAVE: 'You unexpectedly left the review',
    TOAST_WORD_NOT_REMEMBERED: 'The word will be supposed not remembered',
    TOAST_RIGHT_ANSWER: 'right answer ;)',
    TOAST_WRONG_ANSWER: 'You got it wrong :(',
    TOAST_REVIEW_DONE: 'Your vocabulary review is done',
    TOAST_SEARCH_NO_RESULT: 'no result',
    TOAST_DELETED: 'deleted',
    TOAST_VOC_LIST_CLEARED: 'vocabulary list cleared',
    TOAST_MULTI_DEL_ON: 'Multi deletion is on',
    TOAST_MULTI_DEL_OFF: 'Multi deletion is off',
    TOAST_LOG_IN_SUCCESS: 'login successful',
    TOAST_PASSES_DONT_MATCH: `Both passwords don't match`,
    TOAST_ENTER_SAME_PASS: `Please enter same the password`,
    TOAST_WORD_ADDED_IN_VOC: 'added to vocabulary list',
    TOAST_ALREADY_IN_VOC: 'Word/expression already in vocabulary',
    TOAST_ERROR: 'Oops! An internal error occured :(',
    TOAST_NO_WORD_FOUND: 'No word/expression matching preferences found',
    TOAST_CHANGE_PREFS: 'Please change preferences in settings',
    TOAST_EMAIL_ALREADY_IN_USE: 'E-mail is already registered',
    TOAST_LOGIN_INSTEAD: 'Please log in instead',
    TOAST_INVALID_EMAIL: 'invalid e-mail',
    TOAST_OPERATION_NOT_ALLOWED: 'operation not allowed',
    TOAST_WEAK_PASSWORD: 'weak password',
    TOAST_DIFFICULT_PASSWORD: 'Please create a difficult one',
    TOAST_USER_DISABLED: 'This account has been disabled',
    TOAST_USER_NOT_FOUND: 'Account not found',
    TOAST_PLEASE_SIGNUP: 'Please sign up if this is your first use',
    TOAST_WRONG_PASSWORD: 'wrong password',
    TOAST_ACCOUNT_DELETED: 'Your account has been deleted',
    TOAST_ACCOUNT_DISABLED: 'Account temporarily disabled',

})

export default ToastConstants;