import Strings from './Strings'

const UsedLibrariesList = Object.freeze({
    LIBRARIES_ARRAY: [
        Strings.STRING_AXIOS,
        Strings.STRING_AXIOS_LINK,
        Strings.STRING_MOBX,
        Strings.STRING_MOBX_LINK,
        Strings.STRING_REACT_NATIVE_ANIMATABLE,
        Strings.STRING_REACT_NATIVE_ANIMATABLE_LINK,
        Strings.STRING_REACT_NATIVE_ELEMENTS,
        Strings.STRING_REACT_NATIVE_ELEMENTS_LINK,
        Strings.STRING_REACT_NATIVE_FIREBASE,
        Strings.STRING_REACT_NATIVE_FIREBASE_LINK,
        Strings.STRING_REACT_NATIVE_INDICATORS,
        Strings.STRING_REACT_NATIVE_INDICATORS_LINK,
        Strings.STRING_REACT_NATIVE_POPUP_MENU,
        Strings.STRING_REACT_NATIVE_POPUP_MENU_LINK,
        Strings.STRING_REACT_NATIVE_SNACKBAR,
        Strings.STRING_REACT_NATIVE_SNACKBAR_LINK,
        Strings.STRING_REACT_NATIVE_VECTOR_ICONS,
        Strings.STRING_REACT_NATIVE_VECTOR_ICONS_LINK,
        Strings.STRING_REACT_NAVIGATION,
        Strings.STRING_REACT_NAVIGATION_LINK,
        Strings.STRING_REALM,
        Strings.STRING_REALM_LINK
    ]
})

export default UsedLibrariesList;